<div class ="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-right">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="#">ออกจากระบบ</a>
        </li>
        </ul>
    </div>
    </nav>
</div>

<div class ="container">
        <div class="card border-secondary mb-3" style="max-width">
            <div class="card-header">รายละเอียดวิชา</div>
            <div class="card-body text-secondary">
                <h5 class="card-title">Secondary card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>

        <div class="card border-secondary mb-3" style="max-width">
            <div class="card-header">Header</div>
            <div class="card-body text-secondary">
                <h5 class="card-title">Secondary card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>

        <div class="card border-secondary mb-3" style="max-width">
            <div class="card-header">Header</div>
            <div class="card-body text-secondary">
                <h5 class="card-title">Secondary card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>

        <div class="card border-secondary mb-3" style="max-width">
            <div class="card-header">Header</div>
            <div class="card-body text-secondary">
                <h5 class="card-title">Secondary card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
<?php
    echo $this->tag->form(
        [
            "review/addComment",
            "autocomplete" => "off"
        ]
        );
?>
        <div class="card border-secondary mb-3" style="max-width">
            <div class="card-header">แสดงความคิดเห็น</div>
            <div class="card-body text-secondary">
                <textarea rows="4" cols="150" name="comment"></textarea>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">แสดงความคิดเห็น</button>
                    <button type="button" class="btn btn-primary">ยกเลิก</button>
                </div>
            </div>
            
        </div>
        <?php echo $this->tag->endForm();?>
</div>




