<div class="container">
<form id="signin-form">
            <div class="row">
               <div class="col-md-12">
                  <div class="form-group">
                     <label>Username</label>
                     <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-user" aria-hidden="true"></i></span>
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username" >
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <div class="form-group">
                     <label>Password</label>
                     <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-key" aria-hidden="true"></i></span>
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password" >
                     </div>
                  </div>
               </div>
            </div>
            <button type="submit" class="btn btn-info pull-right" id="signin">Sign in</button>
</form>
</div>